FROM tmozgacheva/orca-a
RUN brew install \ 
a5 \
abacas \
abyss-explorer \
abyss \
ace-corrector \
adam \
adapterremoval \
afra \
#allpaths-lg \ old, used discovardenovo
amos \
andi \
# RUN brew install anvio
arcs \
art \
artemis \
astral \
autoconf \
automake \
atram 
RUN brew install augustus

RUN brew install bam-readcount \
bamhash \
bamm \
bamtools \
bamutil \
barrnap \
bbtools \
bcalm \
bcftools \
beagle \
beast \
beast2 \
bedops \
bedtools \
beetl \
bfc \
bioawk \
biobloomtools \
biointerchange \
biomake \
bison \
# biopieces \ for future, export variables
blasr \
blast \
blat \
bless \
bowtie \
bowtie2 \
#bpipe \
breseq \
busco \
bwa 

RUN brew install canu \
cap3 \
cd-hit \
cegma \
celera-assembler \
centrifuge \
cerulean \
circlator \
clark \
clonalframeml \
clonehd \
clustal-omega \
clustal-w \
cmake \
curl \
cufflinks \
# RUN brew install corset
cytoscape
RUN brew install daligner \
dazz_db \
# RUN brew install delly
dextractor \
diamond \
dida \
discovar \
# discovardenovo error =(
dsk \
dwgsim
RUN brew install e-mem \
edirect \
emacs \
# RUN brew install ensembl-tools no formulae
exonerate 
# express

RUN brew install fasta \
fastml \
fastq-tools \
fastqc \
fasttree \
fastuniq \
fastx_toolkit \
fermi-lite \
fermi \
fermi2 \
fermikit \
flash \
flex \
fqzcomp \
freebayes \
freec \
fsa \
fwdpp
RUN brew install gaemr
# RUN brew install garli
RUN brew install gatb
RUN brew install gatk
RUN brew install geneid
RUN brew install genewise
RUN brew install genometools


