FROM tmozgacheva/orca-a
RUN brew install \ 
a5 \
abacas \
abyss-explorer \
abyss \
ace-corrector \
adam \
adapterremoval \
afra \
#allpaths-lg \ old, used discovardenovo
amos \
andi \
# RUN brew install anvio
arcs \
art \
artemis \
astral \
autoconf \
automake \
atram 
RUN brew install augustus

RUN brew install bam-readcount \
bamhash \
bamm \
bamtools \
bamutil \
barrnap \
bbtools \
bcalm \
bcftools \
beagle \
beast \
beast2 \
bedops \
bedtools \
beetl \
bfc \
bioawk \
biobloomtools \
biointerchange \
biomake \
bison \
# biopieces \ for future, export variables
blasr \
blast \
blat \
bless \
bowtie \
bowtie2 \
#bpipe \
breseq \
busco \
bwa 

RUN brew install canu \
cap3 \
cd-hit \
cegma \
celera-assembler \
centrifuge \
cerulean \
circlator \
clark \
clonalframeml \
clonehd \
clustal-omega \
clustal-w \
cmake \
curl \
cufflinks \
# RUN brew install corset
cytoscape
RUN brew install daligner \
dazz_db \
# RUN brew install delly
dextractor \
diamond \
dida \
discovar \
# discovardenovo error =(
dsk \
dwgsim
RUN brew install e-mem \
edirect \
emacs \
# RUN brew install ensembl-tools no formulae
exonerate 
# express

RUN brew install fasta \
fastml \
fastq-tools \
fastqc \
fasttree \
fastuniq \
fastx_toolkit \
fermi-lite \
fermi \
fermi2 \
fermikit \
flash \
flex \
fqzcomp \
freebayes \
freec \
fsa \
fwdpp
RUN brew install gaemr
# RUN brew install garli
RUN brew install gatb
RUN brew install gatk
RUN brew install geneid
RUN brew install genewise
RUN brew install genometools

#no such formulae
# RUN brew install gfatools

RUN brew install gingr
RUN brew install glimmerhmm
RUN brew install gmap-gsnap
RUN brew install gnuplot # broke by mummer
RUN brew install grabix
RUN brew install graphlan
RUN brew install gsl
# RUN brew install gubbins
RUN brew install harfbuzz
# RUN brew install harvest-tools
RUN brew install hisat
RUN brew install hisat2
RUN brew install hlaminer
RUN brew install hmmer
RUN brew install hmmer2
#RUN brew install htqc
RUN brew install htsbox
RUN brew install htslib
RUN brew install humann2
RUN brew install icu4c
RUN brew install idba
RUN brew install igv
RUN brew install igvtools
RUN brew install impute2
RUN brew install infernal
RUN brew install iqtree
RUN brew install iva
RUN brew install jellyfish-1.1
RUN brew install jellyfish
RUN brew install jpeg

RUN brew install kaiju \
kallisto \
kat \ 
kent-tools \
kmacs \
kmc \
kmergenie \
kmerstream \
kollector \
kraken


RUN brew install last \
libbigwig \
libpll \
libsequence \
libtool \
lighter \
links-scaffolder \
lobstr \
lsd \
lua \
lumpy-sv 

RUN brew install m4 \
macse \
mafft \
makedepend 
RUN brew install maker \ 
mapsembler2 \
maq \
mash \
# RUN brew install masurca orca, new version, https://github.com/Homebrew/homebrew-science/pull/5772
mcl \
megahit \ 
meme 
# meraculous \ orca
# RUN brew install metaphlan orca, installed by humann2
RUN brew install mhap \
minced \
minia \
miniasm \
minimap \
mir-prefer \
# RUN brew install mira
mitofy \
mlst \
mothur \ 
mrbayes \
multi-worm-tracker \
mummer \ 
muscle 
# musket no formulae 
