FROM tmozgacheva/orca-b
RUN brew install nanopolish \
# RUN brew install ncbi-c++-toolkit
ncl \
newick-utils \
newicktools \
nextflow \
nonpareil \
novoalign \
ntcard \
nxtrim 
RUN brew install oases
# RUN brew install ogdraw
RUN brew install oma

RUN brew install orthofinder
# RUN brew install pagan no formulae
RUN brew install paml
RUN brew install pandaseq
RUN brew install parallel
RUN brew install parsnp
RUN brew install pathd8
RUN brew install pathvisio
# RUN brew install pbh5tools no formulae
# RUN brew install pbsuite 
RUN brew install pcre
RUN brew install pear
RUN brew install phipack
RUN brew install phlawd
RUN brew install phylip
RUN brew install phyml
RUN brew install phyutility
RUN brew install phyx
RUN brew install picard-tools
RUN brew install piler
RUN brew install pilercr
RUN brew install pilon
RUN brew install pixman
# RUN brew install platanus no formulae
RUN brew install plink
RUN brew install pkg-config
# RUN brew install plink2
RUN brew install poa
# RUN brew install populations
# RUN brew install poretools
RUN brew install prodigal
RUN brew install prokka
RUN brew install proteinortho
RUN brew install psmc
# RUN brew install quaff
# RUN brew install quake
RUN brew install quast
RUN brew install quest
RUN brew install quorum
# RUN brew install r8s
RUN brew install racon 
RUN brew install rampart \
rapsearch2 \
raxml \
ray \
rcorrector \
readline \
readseq \
readsim \
# RUN brew install reapr
recon \
repeatmasker \
repeatmodeler \
repeatscout \
rmblast \
rna-star \
rnammer \
ropebwt2

RUN brew install sailfish \
salmon \
sambamba \
samblaster \
samtools@0.1 \
samtools \
scarpa \
sdsl-lite \
seqan \
seqtk \
sequel \
sga \
shrimp \
sickle \
simulate-pcr \
skewer \
smalt \
# RUN brew install smrtanalysis
# snap-aligner \ may be exclude
snap \
snoscan \
snp-sites \
snpeff \
soapdenovo \
sortmerna \
spaced \
spades \
# sparseassembler \ no formulae
spici \
sqlite \
squeezambler \
sratoolkit \
ssake \
# sspace \ no formulae
# sspace-longread \ no formulae
stacks \
stringtie \
szip \
swarm
RUN brew install tagdust \ 
tasr \
tbb \
tbl2asn \
tophat \
trans-abyss \ 
#RUN brew install trans_proteomic_pipeline 
transdecoder \
transrate-tools \
trf \
trimadap \
trimal \
trimmomatic \
trinity \
trnascan 
#RUN brew install ucsc-genome-browser
RUN brew install uproc
RUN brew install vague \
varscan \
vcake \
vcflib \
vcftools \
velvet \
velvetoptimiser \
viennarna \
vsearch \
vt 
RUN brew install weblogo
RUN brew install wiggletools
RUN brew install yaha

