FROM tmozgacheva/orca-b

RUN brew install maker \ 
mapsembler2 \
maq \
mash \
# RUN brew install masurca orca, new version, https://github.com/Homebrew/homebrew-science/pull/5772
mcl \
megahit \ 
meme 
