
FROM tmozgacheva/orca-b
RUN echo $(date +"%T")
RUN brew install canu \
cap3 \
cd-hit \
cegma \
celera-assembler \
centrifuge \
cerulean \
circlator \
clark \
clonalframeml \
clonehd \
clustal-omega \
clustal-w \
cmake \
curl \
cufflinks \
# RUN brew install corset
cytoscape

RUN echo $(date +"%T")
